[package]
name = "miru"
version = "0.1.0"
authors = ["FCMB.UK/Sam <sam@roava.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
config = "0.10"
dotenv = "0.15"
listenfd = "0.3"
chrono = "0.4"
ulid = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-subscriber = "0.2"
