[package]
name = "miru"
version = "0.1.0"
authors = ["FCMB.UK/Sam <sam@roava.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
dotenv = "0.15"
listenfd = "0.3"
chrono = "0.4"
ulid = "0.4.0"
serde = "1"
serde_json = "1"
